### ISSUE TITLE
修改min、max、now的值后尺度异常

### ISSUE THREAD

**Issue by linj0218** [328921371/ruler#11]
html：
`<cs-ruler
          v-if="showruler"
          pointerColor="#2C76F3"
          @post-NumValue="rulerNum"
          :numSize='30'
          :maxNum='maxNum'
          :NowNum='nowNum'
          :minNum='minNum'
          @scroll-end="endEvent"
        />
<button @click="changeruler">click</button>`
data：
`showruler: true,
      maxNum:2020,
      nowNum:1980,
      minNum:1950`
function：
`changeruler () {
      this.maxNum = 1000,
      this.nowNum = 100,
      this.minNum = 10
    }`
预期：最小值10，当前值100，最大值1000
结果：最小值10，当前值10，最大值80
修改函数：
function：
`changeruler () {
      this.showruler = false
      this.$nextTick(() => {
        this.maxNum = 1000,
        this.nowNum = 100,
        this.minNum = 10
        this.showruler = true
      })
    }`
结果正常了

**Comment by linj0218** [comment]
还有一个问题，scroll-end方法会被调用两次

**Comment by 328921371** [comment]
谢谢你发现了这个BUG，我会去修改的

**Comment by linj0218** [comment]
> 谢谢你发现了这个BUG，我会去修改的

今天发现项目启动的时候打开新页签会出现不能滚动的情况，刷新页面就可以滚动，往后都能继续正常使用。只有项目第一次启动会有这个问题。

**Comment by linj0218** [comment]
![image](https://user-images.githubusercontent.com/18085060/79730038-daba7180-8322-11ea-910f-af3059d49506.png)
![image](https://user-images.githubusercontent.com/18085060/79730222-1c4b1c80-8323-11ea-9f51-fc7cfb75af88.png)

**Comment by linj0218** [comment]
不能滚动的时候cs-scrollrule节点只有mouse相关事件，刷新后，mouse事件消失，代替的是touch相关事件

**Comment by 328921371** [comment]
再移动端里面,确实是touch事件,mouse事件一般都是在PC上,我去看看问题

**Comment by 328921371** [comment]
@linj0218 之前重新赋值子组件不更新的BUG我已经修复了,你后面说的这个不能滚动的,我这边复现不了,实在没有办法

**Comment by linj0218** [comment]
> @linj0218 之前重新赋值子组件不更新的BUG我已经修复了,你后面说的这个不能滚动的,我这边复现不了,实在没有办法

多谢大佬。
我来说一下复现步骤，
1，关掉带有插件的tab
2，重新启动项目（包括打开新tab，浏览器不能刷新）
3，插件就会出现不能滚动的情况
