### ISSUE TITLE
初始值设定有BUG

### ISSUE THREAD

**Issue by kiyosunsun** [328921371/ruler#9]

**Comment by 328921371** [comment]
请问是遇到了什么样的问题呢 @LongYue9608

**Comment by kiyosunsun** [comment]
minNum设置为30  NowNum设置为70 ，实际运行后初始值为100,也就是说在minNum不为0的时候，初始值NowNum=NowNum+minNum你可以试下 @328921371

**Comment by 328921371** [comment]
@LongYue9608 十分感谢你提出的这个BUG,确实有这个错误,已经更新了,谢谢你

**Comment by 328921371** [comment]
@LongYue9608 你的另一个需求是什么呢,有时间的话也可以百度搜索 '陈先生的小前端', 我自己的一个博客网站
